import { describe, it, expect, vi, beforeEach } from "vitest";
import { NextRequest } from "next/server";
import { renderBattlecardHtml } from "@/lib/battlecard";

// ── Unit tests for renderBattlecardHtml ──────────────────────

describe("renderBattlecardHtml", () => {
  const baseInput = {
    competitor: {
      name: "Acme Corp",
      url: "https://acme.example",
      trackPricing: true,
      trackFeatures: true,
      trackBlog: false,
      trackJobs: false,
      trackTech: false,
      createdAt: new Date("2026-01-15"),
    },
    changes: [
      {
        changeType: "PRICING" as const,
        severity: "HIGH" as const,
        summary: "Raised Pro plan from $49 to $79/mo",
        details: "Annual pricing also increased proportionally.",
        pageUrl: "https://acme.example/pricing",
        createdAt: new Date("2026-04-20"),
      },
      {
        changeType: "FEATURE" as const,
        severity: "MEDIUM" as const,
        summary: "Added API access to Pro plan",
        details: null,
        pageUrl: null,
        createdAt: new Date("2026-04-18"),
      },
      {
        changeType: "BLOG" as const,
        severity: "LOW" as const,
        summary: "Published roadmap blog post",
        details: null,
        pageUrl: null,
        createdAt: new Date("2026-04-15"),
      },
    ],
    generatedAt: new Date("2026-05-06"),
  };

  it("generates valid HTML with competitor name in title", () => {
    const html = renderBattlecardHtml(baseInput);
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("<title>Battlecard: Acme Corp");
    expect(html).toContain("acme.example");
  });

  it("shows high-impact changes in Key Intel section", () => {
    const html = renderBattlecardHtml(baseInput);
    expect(html).toContain("Key Intel");
    expect(html).toContain("Raised Pro plan from $49 to $79/mo");
  });

  it("includes change log table", () => {
    const html = renderBattlecardHtml(baseInput);
    expect(html).toContain("Change Log");
    expect(html).toContain("Added API access to Pro plan");
    expect(html).toContain("Published roadmap blog post");
  });

  it("shows overview stats", () => {
    const html = renderBattlecardHtml(baseInput);
    // Total changes = 3
    expect(html).toContain(">3<");
    // 1 high-impact
    expect(html).toContain(">1<");
  });

  it("escapes HTML in competitor name and summaries", () => {
    const input = {
      ...baseInput,
      competitor: { ...baseInput.competitor, name: 'Acme <script>alert("xss")</script>' },
      changes: [
        {
          ...baseInput.changes[0],
          summary: 'Price "jumped" to <b>$99</b>',
        },
      ],
    };
    const html = renderBattlecardHtml(input);
    expect(html).not.toContain("<script>");
    expect(html).toContain("&lt;script&gt;");
    expect(html).not.toContain("<b>$99</b>");
    expect(html).toContain("&lt;b&gt;$99&lt;/b&gt;");
  });

  it("handles empty changes gracefully", () => {
    const html = renderBattlecardHtml({
      ...baseInput,
      changes: [],
    });
    expect(html).toContain("No changes detected yet");
    // The section title "Key Intel (High & Critical)" should not render
    expect(html).not.toContain("Key Intel (High");
  });

  it("shows tracking areas", () => {
    const html = renderBattlecardHtml(baseInput);
    expect(html).toContain("Pricing, Features");
  });

  it("includes footer with KompWatch branding", () => {
    const html = renderBattlecardHtml(baseInput);
    expect(html).toContain("Generated by KompWatch");
    expect(html).toContain("kompwatch.com");
  });
});

// ── API route tests ──────────────────────────────────────────

const { mockDb, mockGetCurrentUser } = vi.hoisted(() => ({
  mockDb: {
    competitor: { findUnique: vi.fn() },
    change: { findMany: vi.fn() },
  },
  mockGetCurrentUser: vi.fn(),
}));

vi.mock("@/lib/db", () => ({ db: mockDb }));
vi.mock("@/lib/auth", () => ({ getCurrentUser: mockGetCurrentUser }));

import { GET } from "@/app/api/export/battlecard/route";

function makeReq(search = ""): NextRequest {
  return new NextRequest(`http://localhost/api/export/battlecard${search}`);
}

const mockCompetitor = {
  id: "comp_1",
  userId: "user_1",
  name: "Acme Corp",
  url: "https://acme.example",
  trackPricing: true,
  trackFeatures: true,
  trackBlog: false,
  trackJobs: false,
  trackTech: false,
  createdAt: new Date("2026-01-15"),
};

beforeEach(() => {
  vi.clearAllMocks();
  mockGetCurrentUser.mockResolvedValue({ id: "user_1" });
  mockDb.competitor.findUnique.mockResolvedValue(mockCompetitor);
  mockDb.change.findMany.mockResolvedValue([
    {
      changeType: "PRICING",
      severity: "HIGH",
      summary: "Raised price",
      details: null,
      pageUrl: null,
      createdAt: new Date("2026-04-20"),
    },
  ]);
});

describe("GET /api/export/battlecard", () => {
  it("returns 401 when not authenticated", async () => {
    mockGetCurrentUser.mockResolvedValue(null);
    const res = await GET(makeReq("?competitorId=comp_1"));
    expect(res.status).toBe(401);
  });

  it("returns 400 when competitorId is missing", async () => {
    const res = await GET(makeReq());
    expect(res.status).toBe(400);
  });

  it("returns 404 when competitor does not exist", async () => {
    mockDb.competitor.findUnique.mockResolvedValue(null);
    const res = await GET(makeReq("?competitorId=comp_999"));
    expect(res.status).toBe(404);
  });

  it("returns 404 when competitor belongs to another user", async () => {
    mockDb.competitor.findUnique.mockResolvedValue({
      ...mockCompetitor,
      userId: "other_user",
    });
    const res = await GET(makeReq("?competitorId=comp_1"));
    expect(res.status).toBe(404);
  });

  it("returns HTML battlecard with correct headers", async () => {
    const res = await GET(makeReq("?competitorId=comp_1"));
    expect(res.status).toBe(200);
    expect(res.headers.get("Content-Type")).toMatch(/text\/html/);
    expect(res.headers.get("Content-Disposition")).toMatch(/battlecard-acme-corp/);
    expect(res.headers.get("Content-Disposition")).toMatch(/\.html"/);

    const body = await res.text();
    expect(body).toContain("<!DOCTYPE html>");
    expect(body).toContain("Acme Corp");
    expect(body).toContain("Raised price");
  });

  it("queries changes scoped to the competitor", async () => {
    await GET(makeReq("?competitorId=comp_1"));
    const args = mockDb.change.findMany.mock.calls[0][0];
    expect(args.where.competitorId).toBe("comp_1");
  });
});
