-- CreateEnum
CREATE TYPE "ContentZone" AS ENUM ('POSITIONING', 'MONETIZATION', 'PRODUCT', 'MARKETING', 'TALENT', 'LEGAL', 'OPERATIONS', 'UNKNOWN');

-- AlterTable
ALTER TABLE "Change" ADD COLUMN "contentZone" "ContentZone" NOT NULL DEFAULT 'UNKNOWN';
