import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { verifyShareToken, generateStakeholderReport } from "@/lib/roi";
import { db } from "@/lib/db";
import { StakeholderReportContent } from "@/components/dashboard/stakeholder-report-content";

const siteUrl = "https://kompwatch.com";

// Tokenized shared report — noindex to keep private URLs out of search engines,
// but expose branded OpenGraph + Twitter card so Slack / email / social unfurls
// show a KompWatch preview (drives viewer-to-signup on shared reports).
export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>;
}): Promise<Metadata> {
  const { token } = await params;
  const verified = verifyShareToken(decodeURIComponent(token));

  const periodLabel =
    verified?.period === "7d"
      ? "7-day"
      : verified?.period === "90d"
        ? "90-day"
        : "30-day";
  const title = verified
    ? `Competitor intelligence report — ${periodLabel} summary`
    : "Competitor intelligence report";
  const description =
    "A shared KompWatch stakeholder report — pricing, features, and content changes across tracked competitors, summarized by AI.";

  return {
    title: `${title} · KompWatch`,
    description,
    robots: {
      index: false,
      follow: false,
      nocache: true,
      googleBot: { index: false, follow: false },
    },
    openGraph: {
      title,
      description,
      url: `${siteUrl}/report`,
      siteName: "KompWatch",
      type: "article",
    },
    twitter: {
      card: "summary",
      title,
      description,
    },
  };
}

export default async function SharedReportPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const verified = verifyShareToken(decodeURIComponent(token));
  if (!verified) notFound();

  const user = await db.user.findUnique({
    where: { id: verified.userId },
    select: { id: true, name: true },
  });
  if (!user) notFound();

  const report = await generateStakeholderReport(user.id, verified.period);

  return (
    <div className="mx-auto max-w-3xl px-4 py-10 sm:py-16">
      <div className="mb-6 flex items-center justify-between">
        <a
          href="/?utm_source=shared-report&utm_medium=report-nav&utm_campaign=viewer-to-signup"
          className="text-sm font-bold text-gray-900"
        >
          KompWatch
        </a>
        <a
          href="/pricing?utm_source=shared-report&utm_medium=report-nav&utm_campaign=viewer-to-signup"
          className="text-xs font-medium text-brand-600 hover:text-brand-700"
        >
          Start monitoring &rarr;
        </a>
      </div>
      <StakeholderReportContent report={report} orgName={user.name ?? undefined} />

      {/* Bottom conversion CTA — viewer-to-signup for shared reports */}
      <div className="mt-12 rounded-2xl border border-brand-200 bg-gradient-to-br from-brand-50 to-white p-6 sm:p-8">
        <p className="text-[11px] font-semibold uppercase tracking-wide text-brand-600">
          Powered by KompWatch
        </p>
        <h2 className="mt-2 text-xl font-bold text-gray-900 sm:text-2xl">
          Want a report like this for your competitors?
        </h2>
        <p className="mt-2 text-sm text-gray-600 sm:text-base">
          This report was auto-generated by KompWatch — we monitor competitor
          pricing, features, and content changes, then summarize what matters in
          a weekly digest. Get an instant snapshot of any competitor in seconds,
          no account required.
        </p>
        <div className="mt-5 flex flex-col gap-3 sm:flex-row">
          <a
            href="/free-snapshot?utm_source=shared-report&utm_medium=report-cta&utm_campaign=viewer-to-signup"
            className="inline-flex items-center justify-center rounded-lg bg-brand-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-brand-700"
          >
            Get a free competitor snapshot &rarr;
          </a>
          <a
            href="/pricing?utm_source=shared-report&utm_medium=report-cta&utm_campaign=viewer-to-signup"
            className="inline-flex items-center justify-center rounded-lg border border-gray-300 bg-white px-5 py-2.5 text-sm font-semibold text-gray-900 hover:bg-gray-50"
          >
            See pricing
          </a>
        </div>
        <p className="mt-4 text-xs text-gray-500">
          14-day free trial · No credit card required · Cancel anytime
        </p>
      </div>
    </div>
  );
}
